LedgerHQ/ledger-app-workflows

.github/workflows/reusable_build.yml
.github/workflows/reusable_ragger_tests.yml

For now, only the `skip_stax` input allows to control on which devices the tests run.
This is quite limited, and I have a usecase where **only** Stax is tested, and I would like the test to run only on it, while using these reusable workflows.
So I propose this new input which should bring a bit more flexibility, by allowing the user to specify a list of device on which the tests should run. This directly mutes the `matrix` fields, so there is no "ghost" jobs created then immediately skipped.
Example [with this action](https://github.com/LedgerHQ/app-recovery-check/actions/runs/4372593910).
The downside is that GitHub does not allow lists as input types (there is only `string`, `bool`, `env` and `choice`, very limiting types but it is how it is), so I'm using a string which will be …

Choosing the device(s) on which the tests are running

---

.github/workflows/_check_app_load_params.yml
.github/workflows/reusable_guidelines_enforcer.yml
README.md

Linked to https://github.com/LedgerHQ/ledger-app-database/pull/1
Example of run here:
- success: https://github.com/LedgerHQ/app-boilerplate/actions/runs/4751891736/jobs/8441585970
- failure due to path: https://github.com/LedgerHQ/app-boilerplate/actions/runs/4751870239/jobs/8441533702
- failure due to curve, appname and flags: https://github.com/LedgerHQ/app-boilerplate/actions/runs/4751914032/jobs/8441639080
- failure due to not in database: https://github.com/LedgerHQ/app-boilerplate/actions/runs/4751937642/jobs/8441705687

Add first version of app-params database and checker

---

.github/workflows/_get_workflow_version.yaml
.github/workflows/reusable_guidelines_enforcer.yml

This change will allow private repositories to use the `guidelines_enforcer` workflow, by giving a PAT delegating the access of the private repository to this workflow.
It seems it does not temper with workflows which does **not** provide any token (example [here](https://github.com/LedgerHQ/app-passwords/actions/runs/5375262899)) - i.e all the existing app workflows.

[add] Optional authentication token for GIT operations

---

.github/workflows/_check_clang_static_analyzer.yml
.github/workflows/reusable_build.yml
README.md

Remove `cargo ledger setup` step from Rust workflows. It has been integrated in `app-builder` since `3.6.0` image version.

Remove cargo ledger setup step from Rust workflows.

---

.github/workflows/_get_app_metadata.yml
.github/workflows/reusable_build.yml
.github/workflows/reusable_guidelines_enforcer.yml
.github/workflows/reusable_ragger_tests.yml

Workflow exemples:
- [guidelines](https://github.com/LedgerHQ/app-boilerplate/actions/runs/6956185159?pr=105)
- [build and test](https://github.com/LedgerHQ/app-boilerplate/actions/runs/6956185160?pr=105)

This PR will make the `ledger_app.toml` manifest mandatory, and will drop the support of legacy Rust manifest

---

.github/workflows/reusable_build.yml

Without this, the cmd delete the directory (obj/ for example) before trying to delete its content, which therefore don't exist anymore.

reusable_build.yml: Fix missing maxdepth

---

.github/workflows/_check_app_load_params.yml
.github/workflows/_check_clang_static_analyzer.yml
.github/workflows/_check_clang_static_analyzer_latest_sdk.yml
.github/workflows/_check_icons.yml
.github/workflows/_check_makefile.yml
.github/workflows/_check_readme.yml
.github/workflows/_get_app_manifest.yml
.github/workflows/_get_app_metadata.yml
.github/workflows/reusable_build.yml
.github/workflows/reusable_check_ethereum_sdk.yml
.github/workflows/reusable_lint.yml
.github/workflows/reusable_pypi_deployment.yml
.github/workflows/reusable_ragger_tests.yml
.github/workflows/scripts_checking.yml

When using the reusable workflows we have warnings like
```
Call Ledger guidelines_enforcer / Dispatch check / Check icons
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/download-artifact@v3
```
```
Call Ledger guidelines_enforcer / Dump app information / Get application manifest for supported devices (nanosp)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3
```
```
Check linting using the reusable workflow / Lint check
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, andstor/file-existence-action@v2
```

Fix action warnings due to version update

---

.github/workflows/_check_app_load_params.yml
.github/workflows/_check_clang_static_analyzer.yml
.github/workflows/_check_clang_static_analyzer_latest_sdk.yml
.github/workflows/_check_icons.yml
.github/workflows/_check_makefile.yml
.github/workflows/_get_app_manifest.yml
.github/workflows/reusable_build.yml
.github/workflows/reusable_ragger_tests.yml

From the Action main page https://github.com/actions/upload-artifact, we can see:
`Unlike earlier versions of upload-artifact, uploading to the same artifact via multiple jobs is not supported with v4.`
Revert action version for upload and download to v3.

Revert some action versions

---

.github/workflows/reusable_ragger_tests.yml

This allows to use such config in a CI:
```
ragger_tests_3:
needs: build_application
uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
with:
download_app_binaries_artifact: "ragger_elfs"
test_filter: "'test_1559'"
test_options: "-s -v"
```
And any other command line parameters, linked to specific test condition can be used.

Add new input to ragger workflow to pass a custom test option

---

.github/workflows/reusable_ragger_tests.yml

Change default value for the parameter `test_options`.

Revert "Add new input to ragger workflow to pass a custom test option"

---

.github/workflows/_check_app_load_params.yml
.github/workflows/_check_clang_static_analyzer.yml
.github/workflows/_check_clang_static_analyzer_latest_sdk.yml
.github/workflows/_check_icons.yml
.github/workflows/_check_makefile.yml
.github/workflows/_check_readme.yml
.github/workflows/_get_app_manifest.yml
.github/workflows/_get_app_metadata.yml
.github/workflows/reusable_guidelines_enforcer.yml
.github/workflows/reusable_ragger_tests.yml
scripts/check_all.sh
scripts/check_readme.sh

Add a top script gathering the different check commands in a single place.
This script can be called from the command line, locally or inside a docker.
This is the 1st step to be able to run the equivalent of the Guideline Enforcer workflow from VSCode extension.
This has been tested using the following apps triggering this branch (in a draft PR):
- app-boilerplate
- app-boilerplate-rust
- app-plugin-boilerplate
- app-ethereum
- app-flow

Add top script to run the different Rule Enforcer scripts

---

.github/workflows/reusable_ragger_tests.yml

This allows the caller workflow to specify what image to use when running the ragger tests.

Add optional `container_image` parameter

---

.github/workflows/end_to_end_tests_of_reusable_workflows.yml
scripts/check_all.sh

In case we want to run the script ouside the CI (VSCode extension or manually), the icon check was only taking into account the device pointed by the environment variable `BOLOS_SDK`.
Here, when not specified, we perform a loop on all supported devices to generate all the required manifest, and thus check all icons at once
Additional commit to add the cardano app to the E-2-E swap tests :wink:

Fix icons check for all targets

---

.github/workflows/reusable_build.yml

Use rust manifest path for reusable build when preparing to upload as library.
[Similarly to `Build application` ](https://github.com/LedgerHQ/ledger-app-workflows/blob/4d66aef8b3fa50e78f803b4cb753906591bbbf30/.github/workflows/reusable_build.yml#L85)step in `reusable_build` workflow, we have to use correct path to locate Rust project.

Use rust manifest path for reusable build when preparing to upload as library

---

.github/workflows/end_to_end_tests_of_reusable_workflows.yml
.github/workflows/reusable_ragger_tests.yml
.pre-commit-config.yaml

Some application (specifically Security Key) give secret option to `pytest` when running the tests.
These secrets are stored in the GitHub repo and can be accessed through classic `${{ secrets.name }}`
However currently the only way to pass argument in the reusable workflow is through a workflow *input*, `test_options`. GitHub seems to not allow to pass `secrets` there, probably because they would end up in clear text.
This PR proposes a solution for this, by adding a workflow *secret* (and not *input*) `secret_test_options`, which is also feed to `pytest`.
This way, it is possible to pass secret arguments to `pytest` in the reusable workflow (and they remain hidden).
Example [here](https://github.com/LedgerHQ/app-security-key/actions/runs/13331761370/job/37237474851).

Allow 'secret' options to be given to pytest in the reusable Ragger workflow

---

.github/workflows/reusable_build.yml

:rotating_light:  To be merged in sync with the migration to Debian-based builders. :rotating_light:

Add jq installation to reusable build for Rust CI

---

.github/workflows/reusable_lint.yml

Now that the app-builder comes with LLVM 14

Bump default lint version to clang-format 14

---

.github/workflows/reusable_build.yml

This will allow (for example) building apps with certain Rust features as part of the reusable workflow, by setting `cargo_ledger_build_args` to `--features foo`.

Add argument to customize the build command for Rust apps

---

.github/workflows/reusable_pypi_deployment.yml

Basically all our Python package deployment CIs have the same scheme and behavior
- installing the package
- testing the built package with `twin`
- then, if the CI is triggered by a tag:
- checking the README is up to date and relevant vs. the current version (all packages use `setuptools-scm`)
- pushing the package on pypi.org
- pushing the package on Ledger Jfrog, with signature & attestation
This reusable workflow does just that, but centralized.
It will make maintenance easier. In particular, when the Jfrog will be able to push to public repositories, propagating this  into our Python package CIs will only need a change here.
- Tested on Ledgered [here](https://github.com/LedgerHQ/ledgered/actions/runs/14597756377/job/40948637584) without a flag (so no deployment, but the package …

Reusable Pypi deployment, with Artifactory

---

.github/workflows/reusable_build.yml

- root cause identified in XRP porting (issue with **tr** command)
- no regression in `prepare to upload as a lib` job
https://github.com/LedgerHQ/ledger-app-workflows/actions/runs/17271387951/job/49016841404?pr=139

Fix C_DEVICE_NAME assignment (for apex_p)

---

.github/workflows/reusable_codeql_checks.yml
.github/workflows/reusable_python_checks.yml
.github/workflows/reusable_unit_tests.yml

Add reusable workflows for
- unit tests, tested here:
- https://github.com/LedgerHQ/app-boilerplate/actions/runs/17773993676
- https://github.com/LedgerHQ/app-openpgp/actions/runs/17774858335
- codeql, tested here:
- https://github.com/LedgerHQ/app-boilerplate/actions/runs/17774156145
- https://github.com/LedgerHQ/app-exchange/actions/runs/17774487238
- https://github.com/LedgerHQ/app-nbgl-tests/actions/runs/17774596377
- https://github.com/LedgerHQ/app-openpgp/actions/runs/17774858398
- python checks, tested here:
- https://github.com/LedgerHQ/app-boilerplate/actions/runs/17773993656
- https://github.com/LedgerHQ/app-nbgl-tests/actions/runs/17774585010
- https://github.com/LedgerHQ/app-openpgp/actions/runs/17774858366
- https://github.com/LedgerHQ/app-openpgp/actions/runs/17774858377

Add new reusable workflows for unit-test, codeql and python-check
